# [PRACTICA DE NUMPY]
## [Curso Python para Ciencia de datos]

Los arreglos de numpy son la base de la computación científica en Python
- los dataframes de pandas para análisis de datos (Numpy era la unica base hasta pandas 1.5.3)
- los datos de entrada o salida para hacer Machine Learning con scikit-learn son arreglos de numpy

**Nota:** Es importante familiarizarse con el manejo de arreglos de numpy para poder hacer ciencia de datos con Python e identificar cuando usar un arreglo de numpy o un dataframe de pandas.

**Importe NumPy como np**

In [1]:
import numpy as np

**Cree un arreglo de ceros de 10 elementos**

In [11]:
arreglo_ceros = np.zeros(10)


In [12]:
arreglo_ceros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Cree un arreglo de unos de 10 elementos**

In [9]:
arreglo_unos = np.ones(10)

In [10]:
arreglo_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Cree un arreglo de cincos de 10 elementos**

In [13]:
arreglo_cincos = np.ones(10) * 5


In [14]:
arreglo_cincos

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Cree un arreglo de números enteros Del 10 al 50 (incluido)**

In [15]:
arreglo_10_50 = np.arange(10, 51)


In [16]:
arreglo_10_50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Cree un arreglo de los números enteros pares Del 10 al 50 (incluidos)**

In [17]:
arreglo_pares = np.arange(10, 51, 2)

In [18]:
arreglo_pares

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Crear una matrix de 3x3 con valores del 0 al 8 (incluido)**

In [19]:
matriz_3x3 = np.arange(9).reshape(3, 3)

In [20]:
matriz_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Crear la matriz identidad de 3x3**

In [21]:
matriz2_3x3 = np.eye(3)


In [ ]:
matriz2_3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Use NumPy para generar un numero aleatorio entre 0 y 1**

In [ ]:
numero_aleatorio = np.random.rand()

In [25]:
numero_aleatorio

0.5054868065540208

**Use NumPy para generar un arreglo de 25 números aleatorios que sean de la distribucion normal estandar**

In [26]:
arreglo_normal = np.random.randn(25)

In [27]:
arreglo_normal

array([ 3.55234138e-01, -4.26071491e-01,  5.06512887e-01,  2.16956323e-03,
       -4.73109207e-01, -9.29349807e-01,  6.78386121e-01, -2.84945273e-01,
       -1.27137083e+00,  1.25644720e+00,  8.93443349e-01,  1.89833729e-01,
       -3.30287126e-01,  2.02214490e+00, -1.41285586e+00,  2.50480065e+00,
        5.74863846e-01, -2.88620927e-01,  8.67578061e-01, -7.93699915e-02,
       -7.51648554e-01, -1.07848661e+00,  1.46926677e+00,  6.12192920e-01,
       -2.02016775e-01])

**Cree un arreglo de 20 elementos linealmente espaciados entre 0 y 1:**

In [28]:
arreglo_lineal = np.linspace(0, 1, 20)

In [29]:
arreglo_lineal

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Indexacion y seleccion con Numpy**

Crear una matriz con numeros del 1 al 25 y que tenga forma de 5x5



In [31]:
matriz_5x5 = np.arange(1, 26).reshape(5, 5)



In [32]:
matriz_5x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

replique los resultados que siguen:


In [41]:
resultado = matriz_5x5[2::1, 1:]

In [42]:
resultado

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:

resultado = matriz_5x5[2::1, 1:]

20

In [ ]:
# Copie su código aqui

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# Copie su código aqui

array([21, 22, 23, 24, 25])

In [ ]:
# Copie su código aqui

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Obtenga la suma de todos los valores de la matriz**

In [ ]:
# Copie su código aqui

325

**Obtenga la desviación estándar de los valores de la matriz**

In [ ]:
# Copie su código aqui

7.211102550927978

**Obtener la suma de cada una de las columnas de la matriz**

In [ ]:
# Copie su código aqui

array([55, 60, 65, 70, 75])