# [PRACTICA DE NUMPY]
## [Curso Python para Ciencia de datos]

#### ESTUDIANTE: JUAN JOSE LAURA BAUTISTA

Los arreglos de numpy son la base de la computación científica en Python
- los dataframes de pandas para análisis de datos (Numpy era la unica base hasta pandas 1.5.3)
- los datos de entrada o salida para hacer Machine Learning con scikit-learn son arreglos de numpy

**Nota:** Es importante familiarizarse con el manejo de arreglos de numpy para poder hacer ciencia de datos con Python e identificar cuando usar un arreglo de numpy o un dataframe de pandas.

**Importe NumPy como np**

In [1]:
import numpy as np

**Cree un arreglo de ceros de 10 elementos**

In [2]:
arreglo_ceros = np.zeros(10)


In [3]:
arreglo_ceros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Cree un arreglo de unos de 10 elementos**

In [4]:
arreglo_unos = np.ones(10)

In [5]:
arreglo_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Cree un arreglo de cincos de 10 elementos**

In [6]:
arreglo_cincos = np.ones(10) * 5


In [7]:
arreglo_cincos

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Cree un arreglo de números enteros Del 10 al 50 (incluido)**

In [8]:
arreglo_10_50 = np.arange(10, 51)


In [9]:
arreglo_10_50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Cree un arreglo de los números enteros pares Del 10 al 50 (incluidos)**

In [10]:
arreglo_pares = np.arange(10, 51, 2)

In [11]:
arreglo_pares

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Crear una matrix de 3x3 con valores del 0 al 8 (incluido)**

In [12]:
matriz_3x3 = np.arange(9).reshape(3, 3)

In [13]:
matriz_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Crear la matriz identidad de 3x3**

In [14]:
matriz2_3x3 = np.eye(3)


In [15]:
matriz2_3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Use NumPy para generar un numero aleatorio entre 0 y 1**

In [16]:
numero_aleatorio = np.random.rand()

In [17]:
numero_aleatorio

0.48233763328393675

**Use NumPy para generar un arreglo de 25 números aleatorios que sean de la distribucion normal estandar**

In [18]:
arreglo_normal = np.random.randn(25)

In [19]:
arreglo_normal

array([ 0.26262051,  0.27631988,  0.51416409, -0.92630619,  1.53139283,
        0.58625943,  0.49572102, -1.26548848,  0.03407852, -0.04945932,
       -0.14253301, -0.76028713,  0.3147915 , -1.01685645,  0.67518112,
       -0.86038708,  0.24401866,  0.45017104,  0.4636985 ,  0.66761105,
       -0.69488278, -0.94157392,  0.45715386, -0.92346076,  0.17813771])

**Cree un arreglo de 20 elementos linealmente espaciados entre 0 y 1:**

In [20]:
arreglo_lineal = np.linspace(0, 1, 20)

In [21]:
arreglo_lineal

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Indexacion y seleccion con Numpy**

Crear una matriz con numeros del 1 al 25 y que tenga forma de 5x5



In [22]:
matriz_5x5 = np.arange(1, 26).reshape(5, 5)



In [23]:
matriz_5x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

replique los resultados que siguen:


In [24]:
resultado = matriz_5x5[2::1, 1:]

In [25]:
resultado

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [65]:

matriz_5x5[3, 4]


np.int64(20)

In [ ]:

matriz3 = matriz_5x5[0:3, 1].reshape(-1, 1)

array([[ 2],
       [ 7],
       [12]])

In [63]:
matriz_5x5[4, :]

array([21, 22, 23, 24, 25])

In [64]:
matriz_5x5[3:5, 1:]

array([[17, 18, 19, 20],
       [22, 23, 24, 25]])

**Obtenga la suma de todos los valores de la matriz**

In [30]:
suma_total = matriz_5x5.sum()

In [66]:
suma_total

np.int64(325)

**Obtenga la desviación estándar de los valores de la matriz**

In [67]:
Desviacion = matriz_5x5.std()

In [68]:
Desviacion

np.float64(7.211102550927978)

**Obtener la suma de cada una de las columnas de la matriz**

In [71]:
sumaColumna = matriz_5x5.sum(axis=0)

In [72]:
sumaColumna

array([55, 60, 65, 70, 75])